language: node_js
node_js:
  - lts/*
dist: xenial
git:
  depth: 1
  quiet: true
branches:
  only:
    - master
cache:
  - npm
  - directories:
    - $HOME/.local
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm i
script:
  - NODE_ENV=production npm run ci
deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master
