language: node_js
node_js:
  - lts/*
dist: xenial
git:
  depth: 1
  quiet: true
branches:
  only:
    - master
cache: npm
script: NODE_ENV=production npm run ci
deploy:
  provider: s3
  bucket: arkny-aws-serverless-web-app
  acl: public_read
  access_key_id:
    secure: TxczBQrXi2NfxJvCd9EK4AOfJWVzEvxPBhwvsKPllQRnkOHshB+92rf1gv6lpvuLkNfKvRgo8ta7vgtYxp8h1n8WXX8ZtcST0Ks+0nJDF9sfmRqdztmMtKk41PrFWVokQ2YsxMLDK73/y/yf6PK/H4PVlOcCQ1D6QY9kKRGVTG/kedri3zVKgSSKCB/Lwx4sV1bebKJfY0n2gH85joyjlDh+3D+EBNOzkPAAxQN1s0H7LP9ZYADU2AFXSD38qmSegIDDBe17TcP2r2zbukRh9r3wE5CBjhXQGXwZQ7yrB33++bsW22H0neJ6OIEfR9/UODIFNINctOUiipSZjmj3M39tFXLn0MyzN0Hl5i24ftJlvk9MCuhyx6Og0jP+0T2T5dKupNGH5ib/T9BfKNeI6MttmmLA9j83hLxwm+JVuVnn7Ns5vfKsRsM8q8D+6lS3wgSpf5bhHd8gaKT7EspqQyNWiUo05xXWY/acfZQ8Wc7s0VGwTboqSpP46iju+p3a9DGfpnDAyI4+kpFuuDny1FYYMy6iZSu1iFQVtRcGKqQmKiW2hi1Nq3c6MXBkwjcS6LMcgOXmBEMx6QAD4qXPfisuyUivfyenPR7I9mksWdno7Qq1+WTON+ukrsBJ2RZaBwu3HAJ9Eh6XaxQXiigT9IHNWlTwNen0xR9CMuzSw0g=
  secret_access_key:
    secure: suLUw9Fp9t4sTSZKY6+PRxtP1fIZ+C3EuiUxk/FYZS+De5C+9JYst5bAIgNcEHjzASrtpgWDQL6TJ+R0PgNknpOAxwg9Sx6+RC3lcjmR20F8YaYGmZFTwemv4Y4HdmfnO8FbXquVxuNNHh8C+AMIjKn7GfNEeQsTmUcs7/hyWFYGaoQf/ffoRWFmQvldriuXb7fGWZQasj17b0OXlz1LllexXLHTXn2sCTUWv2yryWSGE0OpoeAVbNhgVlziEOsIUHKQ0LBc7s1DAwLep7pU8s9hz4X1lmKoZ//WMZ5eNykDAUujEql69a04pzpdfjC7c2JGl0Ymd81GmdH7aIPerEY4G1jlw2+u8fcLw7QxsG2ssBH/eFIxgax7WGAMfC6v4hOmwoDXZa8tv6iYdEqyfDQ+HTdBArBRSaaVU8dWgBmqFexhUaPXyXZpuAqo6wX4VssIPUTYCUWHBLmSqYHxA5tPVzqlBrK5yZrUXNl6VcR6fIRQcn6xDAQuc6crVme2Ve01cVDugFrfFoVU8jZ6HQuBh3uJQuH1WyyEy0EBU0j+x7+y1pbTrD6ZXF5wWUfvFQ6qqU4WTswukFUI3wJvBVSkyKl69SpxIcloTGY2I5abymIk0Gxd7t1mza0lQ7x9ODZP49N1U7Vh+iKC5jEgfQMW4onf8MmMciCbbHpxJhQ=
